# Generated by Django 4.1.3 on 2022-12-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='images', verbose_name='Обложка'),
        ),
    ]
